### ISSUE TITLE
Using spaces in Master-Name generates problems in setup page

### ISSUE THREAD

**Issue by FrankNeeckx** [modal-dsl/modal#22]
When using a master like : 

master "Real Estate Unit" {
    ShortName = "REUnit";

This will generate a setup table definition with :
field(2; "RealEstateUnit Nos."; Code[20])
        {
            Caption = 'RealEstateUnit Nos.';
            TableRelation = "No. Series";

But in the page definition you will get :
field("Real Estate Unit Nos."; "Real Estate Unit Nos.")
                {
                    ApplicationArea = All;
                }

**Comment by joneug** [comment]
Pushed a fix for this issue. It will be made available in the next release of mdAL (and its corresponding VS Code extension).

**Comment by FrankNeeckx** [comment]
Great I'm looking forward to test more of this nice product.

Met vriendelijke groeten,
Sincères salutations,
With kind regards,
Frank


________________________________
Frank Neeckx | project team
t: +32 9 296 31 14


[Herbekijk de webinars voor projectontwikkelaar, bouwbedrijf en installateur]<https://www.astena.be/nl/erp-software/kennisbank-erp>

[cid:image002.png@01D6DC6F.14DC22A0]<https://www.astena.be/nl/erp-software/>



Van: Jonathan Neugebauer <notifications@github.com>
Verzonden: zondag 27 december 2020 14:26
Aan: mdal-lang/mdal <mdal@noreply.github.com>
CC: Frank Neeckx <fn@astena.be>; Author <author@noreply.github.com>
Onderwerp: Re: [mdal-lang/mdal] Using spaces in Master-Name generates problems in setup page (#22)


Pushed a fix for this issue. It will be made available in the next release of mdAL (and its corresponding VS Code extension).

-
